server:
  port: 8091

spring:
  datasource:
    url: jdbc:p6spy:h2:mem:persistence;DB_CLOSE_ON_EXIT=FALSE
    data-username: sa
    data-password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver